const api = window.surfJudgingDesktop;
const state = { candidates: [], selected: null, health: null, prerequisites: null, preparation: null, preparing: false, organization: null, pendingLogoDataUrl: null, priorityDisplay: null };
const $ = (id) => document.getElementById(id);
const defaultLogo = './assets/surfjudging-field-logo-v2.png';
const actions = document.querySelector('.actions');
if (actions) { actions.insertAdjacentHTML('afterbegin', '<button id="start">Start Field</button><button id="stop">Stop Field</button>'); }
const dashboard = document.querySelector('.grid');
if (dashboard) dashboard.insertAdjacentHTML('beforeend', '<section class="card"><h2>Competition safety</h2><p id="competition">Checking authoritative DB…</p></section><section class="card"><h2>Disk</h2><p id="disk">Checking…</p></section><section class="card"><h2>Internet Live</h2><p id="live-publication">Checking local worker…</p><p class="hint">Publication sortante uniquement. Le jugement reste local.</p></section><section class="card wide"><h2>LAN QR</h2><div id="qr"></div><p class="hint">QR contains only the verified LAN Admin URL.</p></section>');
const setDl = (id, rows) => { $(id).innerHTML = rows.map(([k,v]) => `<dt>${k}</dt><dd>${v ?? '—'}</dd>`).join(''); };
function render() {
  const c = state.selected;
  $('status').textContent = c ? `FIELD FOUND — ${c.host}` : 'FIELD NOT FOUND / sélection manuelle requise';
  $('status').className = `banner ${c ? 'ok' : 'bad'}`;
  setDl('identity', [['Host', c?.host], ['Release', c?.manifest?.releaseId], ['Revision', c?.manifest?.codeRevision], ['Schema', c?.manifest?.expectedSchemaVersion]]);
  setDl('health', Object.entries(state.health ?? {}).map(([k,v]) => [k[0].toUpperCase()+k.slice(1), v]));
  setDl('prereq', [['Application Docker Desktop', state.prerequisites?.dockerDesktop ? 'INSTALLÉE':state.prerequisites?.dockerDaemon ? 'NON REQUISE':'NON INSTALLÉE'], ['Commande Docker', state.prerequisites?.dockerCli ? 'DISPONIBLE':'INTROUVABLE'], ['Moteur Docker compatible', state.prerequisites?.dockerDaemon ? 'PRÊT':'ARRÊTÉ']]);
  const urls = c ? c.urls : {}; $('urls').innerHTML = Object.entries(urls).map(([k,v]) => `<a href="${v}" data-url="${v}">${k.toUpperCase()}<br><small>${v}</small></a>`).join('');
  document.querySelectorAll('[data-url]').forEach((a) => a.onclick = (e) => { e.preventDefault(); api.openUrl(a.dataset.url); });
}
function renderPriorityDisplay(){const output=state.priorityDisplay;if(!output){$('priority-display-status').textContent='État inconnu.';return;}const target=output.target?` · ${output.target.label} ${output.target.width}×${output.target.height}`:'';const priorityOrder=output.outputSignal?.order?.length?output.outputSignal.order.map((color,index)=>`P${index+1} ${color}`).join(' · '):output.outputSignal?.color||'';const signal=priorityOrder?` · ${priorityOrder}${output.outputSignal.reason?` (${output.outputSignal.reason})`:''}`:'';const labels={LIVE:'LIVE — ordre métier Field',TEST:'TEST MATÉRIEL — aucune donnée de compétition',BLACKOUT:'NOIR — sortie sécurisée',STARTING:'Démarrage de la sortie…',NO_EXTERNAL_DISPLAY:'Aucun écran HDMI L2 détecté',ERROR:'Erreur de sortie HDMI',CLOSED:'Sortie fermée'};$('priority-display-status').textContent=`${labels[output.state]||output.state}${signal}${target}${output.lastError?` · ${output.lastError}`:''}`;$('priority-display-open').disabled=!state.selected||output.externalDisplayCount<1;$('priority-display-test').disabled=output.externalDisplayCount<1;$('priority-display-blackout').disabled=output.externalDisplayCount<1;}
function preparationText(preparation) {
  if (!preparation) return { summary:'Analyse du système…', detail:'', action:'Analyser' };
  const architecture = preparation.platform === 'win32' && preparation.arch === 'x64'
    ? 'Intel/AMD x64'
    : preparation.arch === 'x64' ? 'Intel' : preparation.arch === 'arm64' ? 'Apple Silicon' : preparation.arch;
  const system = preparation.platform === 'win32' ? 'Windows 11' : 'macOS';
  const machine = `${system} ${preparation.hostVersion} · ${architecture}`;
  const minimumMemoryGb = Math.round((preparation.minimumMemory || 4 * 1024 ** 3) / 1024 ** 3);
  if (!preparation.memoryOk) return { summary:'Mémoire insuffisante', detail:`${machine} · ${minimumMemoryGb} Go minimum requis.`, action:'Réessayer' };
  if (!preparation.diskOk) return { summary:'Espace disque insuffisant', detail:`${machine} · 20 Go libres minimum requis.`, action:'Réessayer' };
  if (preparation.state === 'APP_TRANSLOCATED') return { summary:'Installation de l’application requise', detail:`${machine} · déplacez SurfJudging Field dans le dossier Applications, puis rouvrez-le.`, action:'À déplacer' };
  if (preparation.state === 'RESTART_REQUIRED') return { summary:'Redémarrage Windows requis', detail:`${machine} · WSL 2 a été préparé. Redémarrez Windows, puis relancez SurfJudging Field.`, action:'Redémarrer Windows' };
  if (preparation.state === 'WSL_REQUIRED') return { summary:'Activation de WSL 2 requise', detail:`${machine} · Windows demandera une autorisation administrateur et pourra nécessiter un redémarrage.`, action:'Préparer WSL 2' };
  if (preparation.state === 'WSL_UPDATE_REQUIRED') return { summary:'Mise à jour de WSL 2 requise', detail:`${machine} · version minimale 2.1.5. Windows demandera une autorisation administrateur.`, action:'Mettre à jour WSL 2' };
  if (preparation.state === 'READY') return { summary:'Machine prête pour SurfJudging Field', detail:`${machine} · un moteur Docker compatible est opérationnel.`, action:'Vérifié' };
  if (preparation.state === 'DOCKER_STOPPED') return { summary:'Docker Desktop est installé mais arrêté', detail:`${machine} · aucun téléchargement nécessaire.`, action:'Démarrer Docker' };
  if (preparation.state === 'DOWNLOAD_REQUIRED') return { summary:'Installation de Docker Desktop requise', detail:`${machine} · version approuvée ${preparation.installer.version} (${Math.round(preparation.installer.sizeBytes/1024/1024)} Mo).`, action:'Préparer cette machine' };
  return { summary:'Préparation automatique indisponible pour cette machine', detail:`${machine} · aucun profil d’installation approuvé.`, action:'Actualiser' };
}
function renderPreparation() { const copy=preparationText(state.preparation); $('preparation-summary').textContent=copy.summary; $('preparation-detail').textContent=copy.detail; $('prepare').textContent=state.preparing?'Préparation en cours…':copy.action; $('prepare').disabled=state.preparing || ['READY','MEMORY_INSUFFICIENT','DISK_INSUFFICIENT','APP_TRANSLOCATED','RESTART_REQUIRED'].includes(state.preparation?.state); }
async function refresh() { $('status').textContent = 'Recherche du Field local…'; state.candidates = await api.discoverFieldCandidates(); state.selected = state.candidates.length === 1 ? state.candidates[0] : null; state.health = await api.getFieldHealth(state.selected?.host); state.prerequisites = await api.getRuntimePrerequisiteStatus(); state.preparation=await api.inspectMachinePreparation(); state.priorityDisplay=await api.getPriorityDisplayStatus(); render(); renderPreparation(); renderPriorityDisplay(); const safety=await api.getCompetitionSafety(); $('competition').textContent=safety.runningCount?`RUNNING HEATS = ${safety.runningCount} — STOP FIELD bloqué`:'RUNNING HEATS = 0 — STOP FIELD autorisable après confirmation'; const disk=await api.getDiskStatus(); $('disk').textContent=disk.status==='UNKNOWN'?'UNKNOWN':`${disk.status} — ${Math.round(disk.available/1024/1024/1024)} GB available`; const live=await api.getLivePublicationStatus(); $('live-publication').textContent=live.configured?`${live.state}${live.restartCount?` · relances ${live.restartCount}`:''}${live.lastError?` · ${live.lastError}`:''}`:live.state==='NOT_PROVISIONED'?'Non provisionné — aucune publication externe.':'Désactivé — aucune publication externe.'; if(state.selected){if(state.organization?.configured)await api.syncOrganizationProfile();const qr=await api.generateQr(state.selected.urls.admin); $('qr').innerHTML=`<img alt="Admin LAN QR" width="220" src="${qr}">`;}}
async function openPriorityDisplay(){if(!state.selected)return;try{state.priorityDisplay=await api.openPriorityDisplay(state.selected.host,$('priority-display-podium').value);renderPriorityDisplay();}catch(error){$('priority-display-status').textContent=String(error.message||error).replace(/^Error invoking remote method '[^']+': Error: /,'');}}
async function blackoutPriorityDisplay(){try{state.priorityDisplay=await api.blackoutPriorityDisplay();renderPriorityDisplay();}catch(error){$('priority-display-status').textContent=String(error.message||error).replace(/^Error invoking remote method '[^']+': Error: /,'');}}
async function testPriorityDisplayColor(){try{const pattern=$('priority-display-test-color').value;state.priorityDisplay=pattern.startsWith('ORDER_')?await api.testPriorityDisplayOrder(Number(pattern.split('_')[1])):await api.testPriorityDisplayColor(pattern);renderPriorityDisplay();}catch(error){$('priority-display-status').textContent=String(error.message||error).replace(/^Error invoking remote method '[^']+': Error: /,'');}}
async function diagnostics() { const snapshot = { desktopVersion: await api.getDesktopVersion(), selected: state.selected, candidates: state.candidates, health: state.health, prerequisites: state.prerequisites, preparation: state.preparation, fieldState: await api.getFieldState(), fieldLogs: await api.getFieldLogs(), generatedAt: new Date().toISOString() }; await api.copyDiagnostics(snapshot); $('status').textContent = 'Diagnostic copié (données non secrètes).'; }
function applyOrganization(profile){state.organization=profile;$('organization-label').textContent=profile.configured?profile.organizationName.toUpperCase():'SURFJUDGING';$('app-logo').src=profile.logoDataUrl||defaultLogo;}
function openOrganizationSetup(){const profile=state.organization||{configured:false,organizationName:'',logoDataUrl:null};state.pendingLogoDataUrl=profile.logoDataUrl;$('organization-name').value=profile.organizationName;$('organization-logo-preview').src=profile.logoDataUrl||defaultLogo;$('organization-error').textContent='';$('organization-close').hidden=!profile.configured;$('organization-overlay').hidden=false;$('organization-name').focus();}
async function initializeOrganization(){const profile=await api.getOrganizationProfile();applyOrganization(profile);if(!profile.configured)openOrganizationSetup();}
async function chooseOrganizationLogo(){try{const logo=await api.chooseOrganizationLogo();if(!logo)return;state.pendingLogoDataUrl=logo;$('organization-logo-preview').src=logo;$('organization-error').textContent='';}catch(error){$('organization-error').textContent=String(error.message||error);}}
async function saveOrganization(event){event.preventDefault();if(!state.pendingLogoDataUrl){$('organization-error').textContent='Choisissez le logo de l’organisation.';return;}$('organization-save').disabled=true;try{const profile=await api.saveOrganizationProfile({organizationName:$('organization-name').value,logoDataUrl:state.pendingLogoDataUrl});applyOrganization(profile);$('organization-overlay').hidden=true;}catch(error){$('organization-error').textContent=String(error.message||error).replace(/^Error invoking remote method '[^']+': Error: /,'');}finally{$('organization-save').disabled=false;}}
const stageLabel=(line)=>{if(!line)return'Démarrage contrôlé…';if(line.includes('staging-config'))return'Préparation de la configuration locale persistante…';if(line.includes('image-ready'))return`Vérification des images — ${line.split('image-ready ')[1]||''}`;if(line.includes('image-load'))return`Premier chargement des images — ${line.split('image-load ')[1]||''}`;if(line.includes('kong-config'))return'Préparation sécurisée de la passerelle locale…';if(line.includes('compose-start'))return'Démarrage des services Field…';if(line.includes('compose-finished'))return'Vérification de l’identité Field…';return'Démarrage Field en cours…';};
async function start(){ $('status').textContent='Démarrage contrôlé…'; $('status').className='banner'; const progressTimer=setInterval(async()=>{try{const progress=await api.getFieldProgress();$('status').textContent=stageLabel(progress.lastLog);}catch{}},1000); try{const r=await api.startField(); $('status').textContent=`${r.result||'READY'} — Field`; await refresh()}catch(e){const message=String(e.message||e).replace(/^Error invoking remote method '[^']+': Error: /,'');const logs=await api.getFieldLogs().catch(()=>[]);$('status').textContent=`Démarrage interrompu — ${message}${logs.length?` · ${logs.at(-1)}`:''}`;$('status').className='banner bad';}finally{clearInterval(progressTimer);}}
async function stop(){const gate=await api.canStopField(); if(!gate.allowed){$('status').textContent='STOP DENIED — une heat est en cours.';return} if(!confirm('Arrêter les services Field ? Les données persistantes sont conservées.'))return; const r=await api.stopField(true); $('status').textContent=r.result;}
async function prepareMachine(){
  if(state.preparing)return;
  state.preparation=await api.inspectMachinePreparation(); renderPreparation();
  if(state.preparation.state==='READY')return;
  if(['UNSUPPORTED','MEMORY_INSUFFICIENT','DISK_INSUFFICIENT','APP_TRANSLOCATED','RESTART_REQUIRED'].includes(state.preparation.state)){ $('status').textContent=state.preparation.state==='MEMORY_INSUFFICIENT'?'Préparation bloquée — cette machine ne dispose pas de la mémoire minimale requise.':state.preparation.state==='DISK_INSUFFICIENT'?'Préparation bloquée — libérez au moins 20 Go sur le disque.':state.preparation.state==='APP_TRANSLOCATED'?'Déplacez SurfJudging Field dans Applications, puis rouvrez-le.':state.preparation.state==='RESTART_REQUIRED'?'Redémarrez Windows, puis relancez SurfJudging Field.':'Préparation bloquée — ce système ou cette architecture n’a pas de profil approuvé.'; return; }
  if(['WSL_REQUIRED','WSL_UPDATE_REQUIRED'].includes(state.preparation.state)){
    const accepted=confirm(`${state.preparation.state==='WSL_REQUIRED'?'WSL 2 doit être activé':'WSL 2 doit être mis à jour'} pour exécuter le Field local. Windows affichera une demande d’autorisation administrateur et un redémarrage pourra être nécessaire.\n\nContinuer ?`);
    if(!accepted)return;
  }
  if(state.preparation.state==='DOWNLOAD_REQUIRED'){
    const size=Math.round(state.preparation.installer.sizeBytes/1024/1024);
    const installDetail=state.preparation.platform==='win32'?'l’installer pour votre compte Windows avec le moteur WSL 2':'macOS demandera le mot de passe administrateur pour l’installation';
    const accepted=confirm(`SurfJudging va télécharger ${size} Mo depuis le site officiel Docker, vérifier le fichier et sa signature Docker Inc, puis ${installDetail}.\n\nLa licence Docker restera à accepter dans la fenêtre Docker lors du premier démarrage. Continuer ?`);
    if(!accepted)return;
  }
  state.preparing=true; renderPreparation(); $('status').textContent='Préparation sécurisée de la machine…';
  try{ const result=state.preparation.state==='DOCKER_STOPPED'?await api.launchDockerDesktop():await api.installRuntimePrerequisites(true); $('status').textContent=result?.state==='RESTART_REQUIRED'?'Préparation WSL terminée — redémarrez Windows puis relancez SurfJudging Field.':'Machine prête — Docker est opérationnel.'; }
  catch(error){ $('status').textContent=`Préparation interrompue — ${String(error.message||error).replace(/^Error invoking remote method '[^']+': Error: /,'')}`; }
  finally{state.preparing=false;await refresh();}
}
api.onMachinePreparationProgress((progress)=>{const box=$('preparation-progress');box.hidden=false;const value=Number(progress.percent||0);box.querySelector('span').style.width=`${value}%`;const labels={'download-start':'Téléchargement officiel…',download:'Téléchargement officiel…','verified-download':'Téléchargement vérifié.','verified-cache':'Installateur déjà vérifié.','signature-verification':'Vérification de la signature Docker Inc…','admin-installation':'Installation autorisée par macOS…','user-installation':'Installation Docker Desktop pour ce compte Windows…','wsl-install':'Activation de WSL 2 par Windows…','wsl-update':'Mise à jour de WSL 2 par Windows…','docker-first-start':'Premier démarrage Docker…','docker-starting':'Démarrage du moteur Docker…'};$('preparation-detail').textContent=labels[progress.phase]||progress.phase;});
$('refresh').onclick = refresh; $('start').onclick=start; $('stop').onclick=stop; $('prepare').onclick=prepareMachine; $('copy').onclick = diagnostics;$('organization-settings').onclick=openOrganizationSetup;$('organization-logo-choose').onclick=chooseOrganizationLogo;$('organization-form').onsubmit=saveOrganization;$('organization-close').onclick=()=>{$('organization-overlay').hidden=true;};$('priority-display-open').onclick=openPriorityDisplay;$('priority-display-test').onclick=testPriorityDisplayColor;$('priority-display-blackout').onclick=blackoutPriorityDisplay;initializeOrganization().finally(()=>{refresh();window.setInterval(async()=>{try{state.priorityDisplay=await api.getPriorityDisplayStatus();renderPriorityDisplay();}catch{}},1000);});
