_format_version: "1.1"

services:
  - name: auth
    url: http://surfjudging_auth:9999
    routes:
      - name: auth
        paths:
          - /auth/v1
        strip_path: true
  - name: rest
    url: http://surfjudging_rest:3000
    routes:
      - name: rest
        paths:
          - /rest/v1
        strip_path: true
  - name: realtime
    url: http://surfjudging_realtime:4000
    routes:
      - name: realtime
        paths:
          - /realtime/v1
        strip_path: true
  - name: storage
    url: http://surfjudging_storage:5000
    routes:
      - name: storage
        paths:
          - /storage/v1
        strip_path: true
plugins:
  - name: cors
    config:
      origins:
        - '*'
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
        - apikey
        - Prefer
        - Range
        - accept-profile
        - content-profile
        - x-client-info
      exposed_headers:
        - Content-Range
        - Content-Length
        - Content-Type
      credentials: true
      max_age: 86400
