_format_version: "1.1"

services:
  - name: auth
    url: http://auth:9999
    routes:
      - name: auth
        paths:
          - /auth/v1
        strip_path: true
  - name: rest
    url: http://rest:3000
    routes:
      - name: rest
        paths:
          - /rest/v1
        strip_path: true
  - name: realtime
    url: http://realtime:4000
    routes:
      - name: realtime
        paths:
          - /realtime/v1
        strip_path: true
  - name: storage
    url: http://storage:5000
    routes:
      - name: storage
        paths:
          - /storage/v1
        strip_path: true
