BEGIN;

CREATE TABLE IF NOT EXISTS public.interference_calls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  heat_id TEXT NOT NULL REFERENCES public.heats(id) ON DELETE CASCADE,
  competition TEXT NULL,
  division TEXT NULL,
  round INTEGER NULL,
  judge_id TEXT NOT NULL,
  judge_name TEXT NULL,
  surfer TEXT NOT NULL,
  wave_number INTEGER NOT NULL CHECK (wave_number > 0),
  call_type TEXT NOT NULL CHECK (call_type IN ('INT1', 'INT2')),
  is_head_judge_override BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_interference_calls_heat_id
  ON public.interference_calls(heat_id);

CREATE INDEX IF NOT EXISTS idx_interference_calls_event_id
  ON public.interference_calls(event_id);

CREATE INDEX IF NOT EXISTS idx_interference_calls_surfer
  ON public.interference_calls(heat_id, surfer);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'interference_calls_heat_judge_surfer_wave_key'
  ) THEN
    ALTER TABLE public.interference_calls
      ADD CONSTRAINT interference_calls_heat_judge_surfer_wave_key
      UNIQUE (heat_id, judge_id, surfer, wave_number);
  END IF;
END
$$;

CREATE OR REPLACE FUNCTION public.touch_interference_calls_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_interference_calls_updated_at ON public.interference_calls;
CREATE TRIGGER trg_interference_calls_updated_at
BEFORE UPDATE ON public.interference_calls
FOR EACH ROW
EXECUTE FUNCTION public.touch_interference_calls_updated_at();

ALTER TABLE public.interference_calls ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS interference_calls_read_all ON public.interference_calls;
CREATE POLICY interference_calls_read_all
ON public.interference_calls
FOR SELECT
USING (TRUE);

DROP POLICY IF EXISTS interference_calls_insert_all ON public.interference_calls;
CREATE POLICY interference_calls_insert_all
ON public.interference_calls
FOR INSERT
WITH CHECK (TRUE);

DROP POLICY IF EXISTS interference_calls_update_all ON public.interference_calls;
CREATE POLICY interference_calls_update_all
ON public.interference_calls
FOR UPDATE
USING (TRUE)
WITH CHECK (TRUE);

DROP POLICY IF EXISTS interference_calls_delete_all ON public.interference_calls;
CREATE POLICY interference_calls_delete_all
ON public.interference_calls
FOR DELETE
USING (TRUE);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.interference_calls TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.interference_calls TO authenticated;
GRANT ALL ON TABLE public.interference_calls TO service_role;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_class
    WHERE relkind = 'S'
      AND relname = 'interference_calls_id_seq'
  ) THEN
    EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE public.interference_calls_id_seq TO anon';
    EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE public.interference_calls_id_seq TO authenticated';
    EXECUTE 'GRANT ALL ON SEQUENCE public.interference_calls_id_seq TO service_role';
  END IF;
END
$$;

NOTIFY pgrst, 'reload schema';

COMMIT;
