const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const crypto = require('node:crypto');
const SAFE_CONTAINER = 'surfjudging_postgres';
const PG_DUMP_ARGS = Object.freeze(['--exclude-schema=_realtime','-Fc','-U','postgres','-d','postgres']);
const sha256 = (b) => crypto.createHash('sha256').update(b).digest('hex');
function dataRoot(platform=process.platform,home=os.homedir()) { return platform==='win32' ? path.join(process.env.APPDATA||path.join(home,'AppData','Roaming'),'SurfJudging') : path.join(home,'Library','Application Support','SurfJudging'); }
function layout(root) { return {root,data:path.join(root,'data'),postgres:path.join(root,'data','postgres'),backups:path.join(root,'backups'),logs:path.join(root,'logs'),config:path.join(root,'config'),runtime:path.join(root,'runtime'),images:path.join(root,'images'),diagnostics:path.join(root,'diagnostics')}; }
async function ensureLayout(root) { const l=layout(root); await Promise.all(Object.values(l).map(p=>fs.mkdir(p,{recursive:true,mode:0o700}))); await fs.writeFile(path.join(root,'.surfjudging-data-root.json'),JSON.stringify({version:1,createdAt:new Date().toISOString()},null,2),{mode:0o600}); return l; }
function backupFilename({schema,date=new Date()}) { const stamp=date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z'); return `surfjudging-field-${stamp}-${schema}.dump`; }
function fingerprint(rows) { return crypto.createHash('sha256').update(JSON.stringify(rows)).digest('hex'); }
function createBackupService({execFile,fetchRunningHeats,root,manifest,now=()=>new Date().toISOString()}) { return Object.freeze({async backup(){ const running=await fetchRunningHeats(); if(running.length)return {ok:false,status:'BLOCKED_RUNNING_HEAT',runningHeats:running}; const l=await ensureLayout(root); const file=backupFilename({schema:manifest.schema}); const partial=path.join(l.backups,`${file}.partial`), final=path.join(l.backups,file); try { const {stdout}=await execFile('docker',['exec',SAFE_CONTAINER,'pg_dump',...PG_DUMP_ARGS],{encoding:'buffer',maxBuffer:1024*1024*1024}); if(!stdout?.length)throw new Error('pg_dump produced zero bytes'); await fs.writeFile(partial,stdout,{mode:0o600}); const digest=sha256(stdout); const listed=await execFile('pg_restore',['--list',partial],{encoding:'utf8',maxBuffer:8*1024*1024}); if(!listed.stdout?.trim())throw new Error('pg_restore list failed'); await fs.rename(partial,final); const st=await fs.stat(final); const metadata={backupFormatVersion:1,createdAt:now(),desktopVersion:manifest.desktopVersion,fieldRelease:manifest.frontend.releaseId,sourceRevision:manifest.frontend.sourceRevision,schemaVersion:manifest.schema,databaseVersion:manifest.databaseVersion,databaseName:'postgres',backupFilename:file,backupSize:st.size,sha256:digest,verificationStatus:'VERIFIED',protected:true,reason:'pre-adoption',excludedSchemas:['_realtime']}; await fs.writeFile(`${final}.json`,JSON.stringify(metadata,null,2),{mode:0o600}); return {ok:true,status:'VERIFIED',file,metadata}; } catch(error){ await fs.rm(partial,{force:true}); return {ok:false,status:'FAILED',reason:error.message}; } }}); }
module.exports={dataRoot,layout,ensureLayout,backupFilename,fingerprint,createBackupService,SAFE_CONTAINER,PG_DUMP_ARGS};
