begin;

create table if not exists public.event_category_planning_config (
  event_id bigint not null references public.events(id) on delete cascade,
  category text not null,
  base_format text not null default 'elimination',
  transition_round integer,
  transition_format text,
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (event_id, category),
  constraint event_category_planning_config_base_format_ck
    check (base_format in ('elimination', 'repechage', 'man_on_man')),
  constraint event_category_planning_config_transition_ck
    check (
      (transition_round is null and transition_format is null)
      or (transition_round >= 2 and transition_format is not null and transition_format in ('elimination', 'repechage', 'man_on_man') and transition_format <> base_format)
    )
);

create table if not exists public.heat_progression_edges (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  category text not null,
  target_heat_id text not null,
  target_position integer not null,
  source_round integer not null,
  source_heat text not null,
  source_position integer,
  progression_type text not null,
  created_at timestamptz not null default now(),
  constraint heat_progression_edges_target_position_ck check (target_position > 0),
  constraint heat_progression_edges_source_round_ck check (source_round > 0),
  constraint heat_progression_edges_source_position_ck check (source_position is null or source_position > 0),
  constraint heat_progression_edges_type_ck check (progression_type in ('COMPETITION_RESULT', 'AUTO_ADVANCE_BYE')),
  constraint heat_progression_edges_unique_target unique (event_id, target_heat_id, target_position),
  constraint heat_progression_edges_unique_source unique (event_id, category, source_round, source_heat, source_position, target_heat_id, target_position)
);

create index if not exists event_category_planning_config_event_idx on public.event_category_planning_config(event_id);
create index if not exists heat_progression_edges_event_category_idx on public.heat_progression_edges(event_id, category);

comment on table public.event_category_planning_config is 'P3.8 additive per-category format policy; standard planning data is unchanged.';
comment on table public.heat_progression_edges is 'P3.8 additive progression graph; AUTO_ADVANCE_BYE never creates a sporting heat or score.';

commit;
